name: spacex_flutter_app
description: A Flutter app showcasing SpaceX missions, rockets, and launches using GraphQL API.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.3
  sizer: ^3.1.3
  graphql_flutter: ^5.1.2
  google_fonts: ^4.0.4
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - lib/lang/
    - assets/images/
    - assets/icons/
    - assets/animations/