name: spacex_flutter_app
description: A Flutter app showcasing SpaceX missions, rockets, and launches using GraphQL API.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  provider: ^6.1.5+1
  sizer: ^3.1.3
  shared_preferences: ^2.2.2
  graphql_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/lang/
    - assets/images/
    - assets/icons/
    - assets/animations/